### ISSUE TITLE
Non-issue (Anti-Issue?)

### ISSUE THREAD

**Issue by zach-is-my-name** [rivertam/puzuzu#1]
Just wanted to say thanks for putting me on to the `<text content={ }> `widget in the wonderfully documented blessed/react-blessed.  Discovering your use of it helped me append content to the actual node - as opposed rendering children - whereby the former suddenly populated all of the blessed property fields that I needed, eg. `getScreenLines() `.  On top of it all I got to see my first rust/tsx app in the wild... Cheers!

**Comment by rivertam** [comment]
whoo
